BareBones Logistics Page
david-fisher/320-F20-Track-III pull request #93
Opened 2020-10-07 23:40 UTC by TyGriffin115

There is one bug where I could not figure out how to move the copyright logo to the bottom of the screen. Once that is fixed this should be done. Also I started working on this before the text editors were switched so I am not sure if that will cause a conflict.

2020-10-07 23:49 UTC, TyGriffin115 commented
I merged the master branch into this branch and that fixed the problem with the text editors that I was having

2020-10-08 00:35 UTC, benjaminxu251 submitted a review, later dismissed

2020-10-08 01:26 UTC, Enoch-Hsiao requested changes
Instead of "ch", I would use 100% width for the textboxes.

![Logistics](https://user-images.githubusercontent.com/51762139/95404679-aa23bf80-08e3-11eb-88eb-1dfa3bfb93ff.gif)

2020-10-08 01:32 UTC, Enoch-Hsiao commented
Also if you can remove unused imports, that would be greatly appreciated

2020-10-08 15:13 UTC, Enoch-Hsiao submitted a review, later dismissed

2020-10-08 15:39 UTC, Enoch-Hsiao approved these changes

2020-10-08 15:40 UTC, merged